services:
  db:
    build : ./db
    container_name: db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - mynetwork

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/zakaria/data/db
      o: bind

networks:
  mynetwork:
    driver: bridge
  