FROM node:24-bookworm-slim



WORKDIR /app

COPY package.json package-lock.json* ./

RUN npm install

RUN npm install @nestjs/typeorm typeorm mysql2

RUN npm install @willsoto/nestjs-prometheus prom-client

COPY . .

EXPOSE 8000


CMD ["npm", "run", "start:dev"]



